name: Unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        java_version: ['8', '11', '17', '21']
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java_version }}
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rustflags: "-cfg 'jvm_v${{ matrix.java_version }}'"
    - name: Run tests
      run: cargo test --verbose
